class DuplicateEmailError(Exception): ...
class DuplicateUsernameError(Exception): ...
class InvalidCredentialsError(Exception): ...
class NotFoundError(Exception): ...
class ForbiddenError(Exception): ...
class ValidationError(Exception):
    def __init__(self, field: str, message: str) -> None:
        self.field = field
        self.message = message
        super().__init__(f"{field}: {message}")
